6.3-Added OddNumberExterminator with tests
Dysio9/kodilla-java pull request #1
Opened 2020-10-08 19:32 UTC by Dysio9

2020-10-09 07:00 UTC, MARudnicki requested changes

2020-10-09 07:00 UTC, MARudnicki commented on kodilla-testing/src/main/java/com/kodilla/testing/collection/OddNumberExterminator.java
> +        }
Taki zapis jest bledem - blad powinien zostac wychwycony jak najszybciej, a ta mechanika przerzuca go tylko dalej. Jesli juz to walidacja powinna byc taka
```
 if (numbers == null) {
           throw new IllegalArgumentException();
        }
```

Ale wyjatki sa jeszcze przed toba :-)

2020-10-09 07:00 UTC, MARudnicki commented on kodilla-testing/src/test/java/com/kodilla/testing/collection/CollectionTestSuite.java
> +        OddNumberExterminator oddNumberExterminator = new OddNumberExterminator();
OddNumberExterminator jest bezstanowy i powtarza sie w wielu testach. Lepiej przerzucic go do zmiennej klasowej

2020-10-09 11:47 UTC, Dysio9 commented on kodilla-testing/src/main/java/com/kodilla/testing/collection/OddNumberExterminator.java
> +        }
Tak. Wyjątków się jeszcze nie uczyłem. 
Ja myślałem, że jeżeli pierwszy element będzie nullem (czyli lista będzie pusta) to dalej się to nie wykonuje tylko zwracany jest null. Nie bardzo rozumiem jak "przerzuca go dalej"?

2020-10-09 12:49 UTC, MARudnicki commented on kodilla-testing/src/main/java/com/kodilla/testing/collection/OddNumberExterminator.java
> +        }
Informacje plynie po serwisie, Jesli informacja zawiera blad (np null), trzeba jak najszybciej przerwac procesowanie. 

Przypomnij mi po module w wyjatkami, pokaze Ci to w kodzie

2020-10-10 07:28 UTC, Dysio9 reviewed
zmiany naniesione

2020-10-12 19:16 UTC, merged