14.2 - first commit - calculator (spring - bean configuration/injection)
Dysio9/kodilla-java pull request #21
Opened 2020-12-13 22:30 UTC by Dysio9

2020-12-14 14:06 UTC, MARudnicki requested changes

2020-12-14 14:06 UTC, MARudnicki commented on kodilla-spring/src/main/java/com/kodilla/spring/calculator/Calculator.java
> +    public Calculator() {}
ten konstruktor jest zbedny

2020-12-14 14:06 UTC, MARudnicki commented on kodilla-spring/src/test/java/com/kodilla/spring/calculator/CalculatorTestSuite.java
> +        double divResult = calculator.div(6,3);
to powinny byc 4 testy - po jednym na metode

2020-12-15 09:52 UTC, Dysio9 commented on kodilla-spring/src/test/java/com/kodilla/spring/calculator/CalculatorTestSuite.java
> +        double divResult = calculator.div(6,3);
Też mi się tak wydawało, ale w zadaniu napisano: "Napisz test testCalculations(), który przetestuje poprawność działania czterech metod wykonujących obliczenia." dlatego zrozumiałem, że chodzi o jeden test. Poprawię na cztery oddzielne.

2020-12-19 21:18 UTC, merged