14.3 - first commit - TaskList (spring-configurationClass)
Dysio9/kodilla-java pull request #22
Opened 2020-12-14 12:48 UTC by Dysio9

2020-12-14 14:09 UTC, MARudnicki requested changes

2020-12-14 14:09 UTC, MARudnicki commented on kodilla-spring/src/main/java/com/kodilla/spring/portfolio/Board.java
> +    TaskList doneList;
zmienne powinny byc private

2020-12-14 14:09 UTC, MARudnicki commented on kodilla-spring/src/main/java/com/kodilla/spring/portfolio/TaskList.java
> +    List<String> tasks;
private

2020-12-14 14:09 UTC, MARudnicki commented on kodilla-spring/src/main/java/com/kodilla/spring/portfolio/TaskList.java
> +    }
ten konstruktor jest zbedny. Wystarczy w lini 7 zainicjalizowac liste

2020-12-14 14:09 UTC, MARudnicki commented on kodilla-spring/src/test/java/com/kodilla/spring/portfolio/BoardTestSuite.java
> +        board.showBoard();
Ten test nic nie sprawdza. Brakuje tutaj asercji. 
showBoard mogloby np. zwracac Stringa z komunikatem

2020-12-15 10:03 UTC, Dysio9 commented on kodilla-spring/src/test/java/com/kodilla/spring/portfolio/BoardTestSuite.java
> +        board.showBoard();
Racja. Zmyliło mnie to, że kodilla w swoich materiałach tak robiła. Po prostu wyświetlali wynik w konsoli, bez asercji.

Poprawione.

2020-12-19 21:18 UTC, merged