6.5 mockito(weather forecast)
Dysio9/kodilla-java pull request #3
Opened 2020-10-10 23:11 UTC by Dysio9

Przesyłam do sprawdzenia zadanie z modułu 6.5.

2020-10-11 06:42 UTC, MARudnicki requested changes

2020-10-11 06:42 UTC, MARudnicki commented on kodilla-testing/src/test/java/com/kodilla/testing/weather/mock/WeatherForecastTestSuite.java
> +    void testCalculateForecastWithMock() {
czlon nazwy `WithMock` jest zbedny i tylko zaciemnia test. Analogicznie w pozostalych testach

2020-10-11 06:42 UTC, MARudnicki commented on kodilla-testing/src/test/java/com/kodilla/testing/weather/mock/WeatherForecastTestSuite.java
> +        WeatherForecast weatherForecast = new WeatherForecast(temperaturesMock);
ten element jest tworzony w kazdym tescie, wiec mozna wyciagnac go to zmiennej klasowej
Uzyj np. `@InjectMocks`

2020-10-11 09:43 UTC, Dysio9 commented on kodilla-testing/src/test/java/com/kodilla/testing/weather/mock/WeatherForecastTestSuite.java
> +    void testCalculateForecastWithMock() {
To akurat jest pozostałość po kodzie kodilli :) tej metody akurat nie trzeba było zmieniać :P

2020-10-11 10:00 UTC, Dysio9 commented on kodilla-testing/src/test/java/com/kodilla/testing/weather/mock/WeatherForecastTestSuite.java
> +        WeatherForecast weatherForecast = new WeatherForecast(temperaturesMock);
Poprawki naniesione w nowym commicie.

2020-10-11 10:02 UTC, Dysio9 commented on kodilla-testing/src/test/java/com/kodilla/testing/weather/mock/WeatherForecastTestSuite.java
> +        WeatherForecast weatherForecast = new WeatherForecast(temperaturesMock);
Pytanie organizacyje. Czy jak przesyłasz uwagi to powinienem wycofac pull requesta i wystawić nowego na commicie na którym naniosłem poprawki? Czy ten nowy commit jest już automatycznie podpinany pod tego pull requesta?

2020-10-12 21:13 UTC, Dysio9 commented
Sugestie naniesione

2020-10-13 06:16 UTC, MARudnicki requested changes

2020-10-13 06:16 UTC, MARudnicki commented on kodilla-testing/src/test/java/com/kodilla/testing/weather/mock/WeatherForecastTestSuite.java
> +//        WeatherForecast weatherForecast = new WeatherForecast(temperaturesMock);
usun prosze zakomentowany kod

2020-10-13 06:17 UTC, MARudnicki commented on kodilla-testing/src/test/java/com/kodilla/testing/weather/mock/WeatherForecastTestSuite.java
> +//        WeatherForecast weatherForecast = new WeatherForecast(temperaturesMock);
w pozostalych testach analogicznie

2020-10-15 06:27 UTC, MARudnicki commented on kodilla-testing/src/test/java/com/kodilla/testing/weather/mock/WeatherForecastTestSuite.java
> +        WeatherForecast weatherForecast = new WeatherForecast(temperaturesMock);
nie commit jest automatycznie podpisany do istaniejacego PRa

2020-10-15 06:28 UTC, MARudnicki requested changes

2020-10-15 06:28 UTC, MARudnicki commented on kodilla-testing/src/test/java/com/kodilla/testing/weather/mock/WeatherForecastTestSuite.java
> +    WeatherForecast weatherForecast;
niekonsystencja - raz private raz package-private. W testach enkapsulacja nie jest konieczna, ale warto sie trzymac jednej konwencji

2020-10-15 13:25 UTC, merged